name: "Cloud Foundry Deploy"
description: Deploys your application to Cloud Foundry
author: https://github.com/starkandwayne
requirements:
  - bash
  - cf
configuration:
  properties:
    api:
      type: string
    skip-ssl-validation:
      type: bool
    username:
      type: string
    password_env:
      type: string
    organization:
      type: string
    space:
      type: string
    appname:
      type: string
    manifest_path:
      type: string
    skip-zero-downtime:
      type: bool
  required:
    - api
    - organization
    - space
    - appname
  additionalProperties: false
