steps:
  # - label: ":shell: Shellcheck"
  #   plugins:
  #     shellcheck#v1.1.2:
  #       files: hooks/**

  # - label: ":docker: :hammer:"
  #   plugins:
  #     docker-compose#v3.1.0:
  #       run: tests

  # TODO - what's this test step?
  # - label: ":sparkles:"
  #   plugins:
  #     plugin-linter#v2.0.0:
  #       id: cf

  - wait

  - label: ":cloudfoundry:"
    command: "echo hello world"
    plugins:
      ${BUILDKITE_REPO}#${BUILDKITE_COMMIT}:
        api: https://api.run.pivotal.io
        username: drnic@starkandwayne.com
        organization: starkandwayne
        space: buildkite-plugin-tests
        manifest_path: cf/manifest.yml